AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - extra/*
    - gemfiles/*
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 22

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30

Style/SignalException:
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'lib/health_monitor/providers/**/*'
